name: check-crlf-extended
author: kforeverisback
description: "Checks for non-binary files with CRLF/LF endings in given path"

branding:
  icon: file-text
  color: gray-dark

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.path }}
    - ${{ inputs.exclude }}

inputs:
  directory:
    description: Directory/Folder path to check
    required: false
    default: "."
  line_ending_type:
    description: "Check CRLF/LF or mixed line ending.
      Possible values are CRLF, LF and MIXED (case insensitive).
      CRLF: Checks files only with CRLF line endings.
      LF: Checks files only with LF line endings.
      MIXED: Checks files only with CRLF and LF (mixed) line endings."
    required: false
    default: "crlf"
  include_pattern:
    description: Glob pattern for matching file names (not directory)
    required: false
    default: "*"
  exclude_pattern:
    description: "Comma separated list of glob pattern for excluding file names (not directory). It cannot be *"
    required: false
    default: ""
