name: check-crlf-extended
author: kforeverisback
description: "Checks for non-binary files with CRLF/LF endings in given path. It automatically excludes `.git` folder from search. It will write number of files found (number) and followed by list of files with CRLF/LF/MIXED endings to GITHUB_OUTPUT variable."

branding:
  icon: file-text
  color: blue

runs:
  using: "docker"
  image: "Dockerfile"
  # env:
  #   GITHUB_OUTPUT: ${{ GITHUB_OUTPUT }}
  args:
    - -t
    - ${{ inputs.directory }}
    - -l
    - ${{ inputs.line_ending_type }}
    - -i
    - ${{ inputs.include_regex }}
    - -e
    - ${{ inputs.exclude_regex }}
    - -d
    - ${{ inputs.max_dir_depth }}

inputs:
  directory:
    description: Directory/Folder path to check. Default is `.`, that represents the root of repo ($GITHUB_WORKSPACE)
    required: false
    default: "."
  line_ending_type:
    description: "Check CRLF/LF or mixed line ending.
                  Possible values are CRLF, LF or MIXED (case insensitive).
                  - CRLF: Checks files only with CRLF line endings.
                  - LF: Checks files only with LF line endings.
                  - MIXED: Checks files both with CRLF and LF (mixed) line endings."
    required: false
    default: "crlf"
  include_regex:
    description: "Regular expression for including files (using `find` -regex).
                  Note: The input `directory` will be prepended when forming regex.
                  For example, default `directory` is `.` which is the repo root.
                  So all file paths will have `./` as prefix.
                  Take that into consideration when using regex pattern"
    required: false
    default: ".*"
  exclude_regex:
    description: "Regular expression for excluding files (using `find -not -regex`).
                  Note: see `include_regex` note"
    required: false
    default: "^$"
  max_dir_depth:
    description: "Max depth of folder to search for files. Repo root directory `./` is at depth 1. See `man find` for more information."
    required: false
    default: "999"
