name: check-crlf-extended
author: kforeverisback
description: "Checks for non-binary files with CRLF/LF endings in given path with include/exclude pattern."

branding:
  icon: file-text
  color: blue

runs:
  using: "docker"
  image: "Dockerfile"
  # env:
  #   GITHUB_OUTPUT: ${{ GITHUB_OUTPUT }}
  args:
    - -t
    - ${{ inputs.directory }}
    - -l
    - ${{ inputs.line_ending_type }}
    - -i
    - ${{ inputs.include_pattern }}
    - -e
    - ${{ inputs.exclude_pattern }}
    - -d
    - ${{ inputs.max_dir_depth }}
    - -p
    - ${{ inputs.pattern_type }}


inputs:
  directory:
    description: Directory/Folder path to check. Default is `.`, that represents the root of repo ($GITHUB_WORKSPACE)
    required: false
    default: "."
  line_ending_type:
    description: "Check CRLF/LF or mixed line ending.
                  Possible values are CRLF, LF or MIXED (case insensitive).
                  - CRLF: Checks files only with CRLF line endings.
                  - LF: Checks files only with LF line endings.
                  - MIXED: Checks files both with CRLF and LF (mixed) line endings."
    required: false
    default: "crlf"
  include_pattern:
    description: "Include pattern for including files (using `find -regex` or `find -name`).
                  Note: When pattern_type is `regex`, this is used as regex pattern.
                  When pattern_type is `shell_glob`, this is used as shell glob pattern.
                  For `regex` pattern_type, the match happens on the whole path.
                  For `shell_glob` pattern_type, the path with the leading directories is removed and is operated on base filenames only.
                  The default value `*` is used with the default pattern_type `shell_glob`.
                  See https://man7.org/linux/man-pages/man1/find.1.html for more information."
    required: false
    default: ""
  exclude_pattern:
    description: "Regular expression for excluding files (using `find -not -regex` or `find -not -name`).
                  Note: see `include_pattern` note section"
    required: false
    default: ""
  max_dir_depth:
    description: "Max depth of folder to search for files. Repo root directory `./` is at depth 1. See `man find` for more information."
    required: false
    default: "999"
  pattern_type:
    description: "Type of pattern match to use for `include_pattern` and `exclude_pattern`.
              Possible values are either `shell_glob` or `regex`. Default is `shell_glob`.
              For `regex` pattern_type, the match happens on the whole path.
              For `shell_glob` pattern_type, the path with the leading directories
              is removed and match happens on base filenames only.
              The regex pattern follows egrep syntax. See `man egrep` for more information."
    required: false
    default: "shell_glob"
