name: Regression test for this action

on: [push, pull_request]

jobs:
  action_test:
    runs-on: ubuntu-latest
    name: Running the action after generating test files
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v4
      - name: Generate test files
        run: |
          bash create-test-files.bash "./test-files"
      - name: Check CRLF files
        uses: ./ # Uses an action in the root directory
        id: crlf_check
        continue-on-error: true
        with:
          line_ending_type: 'CRLF'
      - name: Check LF files
        uses: ./ # Uses an action in the root directory
        id: lf_check
        continue-on-error: true
        with:
          directory: ./test-files
          line_ending_type: 'LF'
      - name: Check Mixed files
        uses: ./ # Uses an action in the root directory
        id: mixed_check
        continue-on-error: true
        with:
          directory: ./test-files
          line_ending_type: 'Mixed'
      - name: Check CRLF files with include regex
        uses: ./ # Uses an action in the root directory
        id: crlf_inc_regex_check
        continue-on-error: true
        with:
          directory: ./test-files
          line_ending_type: 'CRLF'
          include_regex: '.*CAP$'
      - name: Check LF files with include regex
        uses: ./ # Uses an action in the root directory
        id: lf_inc_regex_check
        continue-on-error: true
        with:
          directory: ./test-files
          line_ending_type: 'LF'
          include_regex: '.*CAP$'
      - name: Check CRLF files with exclude regex
        uses: ./ # Uses an action in the root directory
        id: crlf_exc_regex_check
        continue-on-error: true
        with:
          directory: ./test-files
          line_ending_type: 'CRLF'
          exclude_regex: '.*EXCLUDE.*'
      - name: Check LF files with exclude regex
        uses: ./ # Uses an action in the root directory
        id: lf_exc_regex_check
        continue-on-error: true
        with:
          directory: ./test-files
          line_ending_type: 'LF'
          exclude_regex: '.*EXCLUDE.*'
      - name: Check file depth for CRLF
        uses: ./ # Uses an action in the root directory
        id: crlf_depth_check
        continue-on-error: true
        with:
          directory: ./test-files
          line_ending_type: 'crLF'
          max_dir_depth: '1'
      # Use the output from the `hello` step
      # - name: Get the output time
      #   run: echo "The time was ${{ steps.hello.outputs.time }}"
