name: Regression test for this action

on: [push, pull_request]

jobs:
  action_test:
    runs-on: ubuntu-latest
    name: Running the action after generating test files
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v4
      - name: Generate test files
        run: |
          bash create-test-files.bash "./test-files"
      - name: Check CRLF files
        uses: ./ # Uses an action in the root directory
        id: crlf_check
        continue-on-error: true
        with:
          line_ending_type: 'CRLF'
      - name: Test CRLF Results
        run: |
          [[ ${{steps.crlf_check.outputs.FILE_COUNT}} == "64" ]] || exit 1
      - name: Check LF files
        uses: ./ # Uses an action in the root directory
        id: lf_check
        continue-on-error: true
        with:
          directory: ./test-files
          line_ending_type: 'LF'
      - name: Test LF Results
        run: |
          [[ ${{steps.lf_check.outputs.FILE_COUNT}} == "64" ]] || exit 1
      - name: Check Mixed files
        uses: ./ # Uses an action in the root directory
        id: mixed_check
        continue-on-error: true
        with:
          directory: ./test-files
          line_ending_type: 'Mixed'
      - name: Test MIXED Results
        run: |
          [[ ${{steps.mixed_check.outputs.FILE_COUNT}} == "64" ]] || exit 1
      - name: "Check CRLF files with glob CRLF*space"
        uses: ./ # Uses an action in the root directory
        id: crlf_glob_check
        continue-on-error: true
        with:
          directory: ./test-files
          line_ending_type: 'CRLF'
          include_pattern: 'CRLF*only'
      - name: Test CRLF files glob CRLF*space Results
        run: |
          [[ ${{steps.crlf_glob_check.outputs.FILE_COUNT}} == "8" ]] || exit 1
      - name: Check LF files with glob LF*space
        uses: ./ # Uses an action in the root directory
        id: lf_glob_check
        continue-on-error: true
        with:
          directory: ./test-files
          line_ending_type: 'LF'
          include_pattern: 'LF*space'
      - name: Test LF files glob LF*space Results
        run: |
          [[ ${{steps.lf_glob_check.outputs.FILE_COUNT}} == "8" ]] || exit 1
      - name: Check LF files with include+exclude glob
        uses: ./ # Uses an action in the root directory
        id: lf_inc_exc_glob_check
        continue-on-error: true
        with:
          directory: ./test-files
          line_ending_type: 'LF'
          include_pattern: 'LF*'
          exclude_pattern: '*only'
      - name: Test LF files include+exclude glob Results
        run: |
          [[ ${{steps.lf_inc_exc_glob_check.outputs.FILE_COUNT}} == "8" ]] || exit 1
      - name: Check CRLF files with include+exclude glob
        uses: ./ # Uses an action in the root directory
        id: crlf_inc_exc_glob_check
        continue-on-error: true
        with:
          directory: ./test-files
          line_ending_type: 'CRLF'
          include_pattern: 'CRLF*'
          exclude_pattern: '*only'
      - name: Test CRLF files include+exclude glob Results
        run: |
          [[ ${{steps.crlf_inc_exc_glob_check.outputs.FILE_COUNT}} == "8" ]] || exit 1
      - name: Check CRLF files with exclude regex
        uses: ./ # Uses an action in the root directory
        id: crlf_exc_regex_check
        continue-on-error: true
        with:
          directory: ./test-files
          line_ending_type: 'CRLF'
          exclude_pattern: '.*(EXCLUDE|exclude).*'
          pattern_type: 'regex'
      - name: Test CRLF files exclude regex Results
        run: |
          [[ ${{steps.crlf_exc_regex_check.outputs.FILE_COUNT}} == "32" ]] || exit 1
      - name: Check LF files with include regex
        uses: ./ # Uses an action in the root directory
        id: lf_exc_regex_check
        continue-on-error: true
        with:
          directory: ./test-files
          line_ending_type: 'LF'
          include_pattern: '.*space$'
          pattern_type: 'regex'
      - name: Test LF files include regex Results
        run: |
          [[ ${{steps.lf_exc_regex_check.outputs.FILE_COUNT}} == "32" ]] || exit 1
      - name: Check file depth for CRLF
        uses: ./ # Uses an action in the root directory
        id: crlf_depth_check
        continue-on-error: true
        with:
          directory: ./test-files
          line_ending_type: 'crLF'
          max_dir_depth: '1'
      # Use the output from the `hello` step
      # - name: Get the output time
      #   run: echo "The time was ${{ steps.hello.outputs.time }}"
      - name: Test CRLF files depth Results
        run: |
          [[ ${{steps.crlf_depth_check.outputs.FILE_COUNT}} == "8" ]] || exit 1
